import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import { cn } from '@/lib/utils';
import { cookies } from 'next/headers';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider, type Theme } from '@/components/ThemeProvider';
import './globals.css';

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-jetbrains-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function resolveInitialTheme(theme: Theme): 'light' | 'dark' {
  if (theme === 'light') return 'light';
  return 'dark';
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookieStore = await cookies();
  const storedTheme = cookieStore.get('theme')?.value;
  const initialTheme: Theme =
    storedTheme === 'light' || storedTheme === 'dark' || storedTheme === 'system'
      ? storedTheme
      : 'dark';
  const initialResolvedTheme = resolveInitialTheme(initialTheme);

  return (
    <html
      lang='en'
      suppressHydrationWarning
      className={cn('h-full', 'antialiased', jetBrainsMono.variable, 'font-mono')}
      style={{ colorScheme: initialResolvedTheme }}
    >
      <body className='min-h-full flex flex-col'>
        <ThemeProvider initialTheme={initialTheme} initialResolvedTheme={initialResolvedTheme}>
          <Navbar />
          {children}
          <Toaster position='top-center' />
        </ThemeProvider>
      </body>
    </html>
  );
}
