import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';
import './globals.css';

const mapleMono = localFont({
  src: [
    { path: './fonts/MapleMonoNormal-Regular.ttf.woff2', weight: '400', style: 'normal' },
    { path: './fonts/MapleMonoNormal-Medium.ttf.woff2', weight: '500', style: 'normal' },
    { path: './fonts/MapleMonoNormal-SemiBold.ttf.woff2', weight: '600', style: 'normal' },
    { path: './fonts/MapleMonoNormal-Bold.ttf.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-maple-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', mapleMono.variable, 'font-mono')}>
      <body className='min-h-full flex flex-col'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
